services:
  db:
    image: postgres:13.3-alpine
    environment:
      POSTGRES_DB: "followup_bot_db"
      POSTGRES_PASSWORD: Jbf4833Tk3Q7
    expose:
      - "51373"
    ports:
      - "51373:51373"
    volumes:
      - ./db_init.sql:/docker-entrypoint-initdb.d/init.sql
    command: -p 51373

  app:
    build: .
    restart: always
    depends_on:
      - db
    stdin_open: true
    tty: true